### ISSUE TITLE
Vercel Deployment

### ISSUE THREAD

**Issue by Micha-Llnsk** [Micha-Llnsk/Lyrify#2]
## Value Statement

As a developer and contributor to this project
I want to see every increment deployed so its easy to test.

## Acceptance Criteria
- Main branch should be deployed after every change.
- Every PR should have a corresponding deployment so it's easy for reviewers to check

## Tasks

* [x] Connect Vercel to this repository
* [x] Double check if its configured properly:
   * [x] Deployments for main branch
   * [x] Deployments for every PR
