### ISSUE TITLE
Add-basic-layout

### ISSUE THREAD

**Issue by Micha-Llnsk** [Micha-Llnsk/Lyrify#3]
## Value Statement

As a user of Lyrify
I want to be able to navigate between the pages:
- Playlists
- Search
- Artists
And I want to be able to visit the site from different devices so I can use the app everywhere I am 

## Description

Setup basic UI, with a header, content and bottom navigation.
Make three pages and link them together.

## Acceptance Criteria

* It should be responsive, working for different screen sizes
* The user should be able to navigate between the Playlists, the search and artists page
* The header should display the title according to the page that's currently selected

## Tasks

* [x] Install react-router-dom
* [x] Define Routes /playlists, /search and /artists
* [x] Make the /route redirect to pages
* [x] Create basic CSS Grid layout
  * [x] Navigation
  * [x] PlaylistsPage
  * [x] SearchPage
  * [x] ArtistsPage
* [x] Basic Design, with text and background color and font 

Make the header change its text depending on the location
