### ISSUE TITLE
Implement Sptify-Api

### ISSUE THREAD

**Issue by Micha-Llnsk** [Micha-Llnsk/Lyrify#4]
## Value Statement

As a user I want to login my Spotify account, to use the Lyrify App.
I will see a landing page, with the option to login or make a Spotify account
and after the login I will land on the Playlists page with the rendered Playlists.

## Description

On the landing Page there is a Logo, a short description of what the user has to do and a login button to Spotify.
When they login, the user should get redirected to the Playlists page and see his/her Playlists in a basic list.

## Tasks

* [x] research the Spotify Api
* [x] Get Authentication for the Api
* [x] make a Home page when not logged in
* [x] Pop-Up to allow access to Spotify Account
* [x] When logged in, land on Playlists Page
* [x] Fetch and render the saved Playlists of the user

## Complexity

Medium/Large
