### ISSUE TITLE
A single Playlist/all songs

### ISSUE THREAD

**Issue by Micha-Llnsk** [Micha-Llnsk/Lyrify#5]
## Value statement

As a user I want to click on my playlist, and that directs me to a list of all songs inside of the playlist.
Every song is also clickable and this directs me to the lyrics of the song.

## Description

Each playlist inside playlists page is clickable
The playlist page shows all songs of the clicked playlist.
Each song can be clicked to show the lyrics to the single song.

## Tasks

* [x] Make every playlist a clickable
* [x] make song list page and lyrics page
* [x] Direct to new page and render songs, each with:
* * [x] title
* * [x] song name
* * [x] small picture 
* [x] Make songs a button to redirect to lyrics page
* [x] Show static lyrics 
* [x] Only show 20 songs per page. Pagination is working with infinite scrolling

## Complexity

middle
