### ISSUE TITLE
Authors page

### ISSUE THREAD

**Issue by Micha-Llnsk** [Micha-Llnsk/Lyrify#6]
## Value statement

As a user I want to see all artist i follow in Spotify on this page and be able to click on them to be directed to a page with a bit of information about the artist and the most heared songs.

## Description

Each artists is clickable
The artists page shows infos about him/her and there is a filtered list of the 10-20 most heared songs on Spotify.

## Tasks

* [x] fetch the followed artists from user:
* * [x] name
* * [x] picture
* [x] make them clickable
* [x] redirect to single artist page with:
* * [x] Infos
* * [x] List of most heared songs
* [x] every song is clickable 
* [x] open lyrics page of a song

## Complexity

middle
