### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by Micha-Llnsk** [Micha-Llnsk/Lyrify#7]
## Value statement

As a user I want to have a search bar in which I can input song names and/or artist names to get a list of most fitting songs.

## Description

There is a search bar in the header so it never disappeares.
User can input song names or artist names and get's 5-10 song recommendations/results,
which can be clicked to get to the single lyrics page.

## Tasks

* [x] Make search input field inside the header
* [x] filter with every written letter
* [x] render list of results in a list with:
* * [x] song name
* * [x] artists name
* * [x] picture
* [x] make them clickable
* [x] redirect to single lyrics page

## Complexity

small
