### ISSUE TITLE
Lyrics-page

### ISSUE THREAD

**Issue by Micha-Llnsk** [Micha-Llnsk/Lyrify#8]
## Value statement

As a user I want to see the lyrics of the song i clicked at.
It should be the right lyrics to the song i wanted.
And I want to have a button to go back to may lists.

## Description

The page of a single song, should render the corresponding lyrics.
With a back button.

## Tasks

* [x] research lyrics-finder npm
* [x] fetch lyrics of a fixed song
* [x] get artist and song name from clicked list item(spotify api) and fetch the specific lyrics
* [x] build - go back button

## Complexity

middle/large
